### ISSUE TITLE
A potential error in the book

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Apress/beginning-rust-2e#1]
The book states:

> The sequence of characters \n (where n stands for new line) is transformed by the compiler into the character sequence that represents the line terminator for the currently used operating system.

This is not true. I created a very simple program:

```
fn main() {
    println!("abc\ndef");
}
```

When I run the program on a Linux machine, I got this:
```
root@u2004:~/rust1# cargo run | od -ta
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/rust1`
0000000   a   b   c  nl   d   e   f  nl
0000010
root@u2004:~/rust1#
```

When I run it on Windows (I installed the od.exe utility on Windows), I got this:
```
c:\rust1>cargo run | od -ta
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target\debug\rust1.exe`
0000000   a   b   c  nl   d   e   f  nl
0000010
c:\rust1>
```

As you can see, the program produced the exactly same result. So "transformed by the compiler into the character sequence that represents the line terminator for the currently used operating system" is not true. As on Windows, the line terminator is `\r\n`, not `\n` (which is the line terminator on Linux).

**Comment by carlomilanesi** [comment]
You are right. When printing "\n", only one character is printed. I tested the code mostly on Linux, and I got confused with the C language behavior.
